apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: prometheus-community
  pass_credentials_all: false
  password: ""
  url: https://prometheus-community.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: redis-ha
  pass_credentials_all: false
  password: ""
  url: https://dandydeveloper.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: grafana
  pass_credentials_all: false
  password: ""
  url: https://grafana.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: netdata
  pass_credentials_all: false
  password: ""
  url: https://netdata.github.io/helmchart
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: external-secrets
  pass_credentials_all: false
  password: ""
  url: https://charts.external-secrets.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: jetstack
  pass_credentials_all: false
  password: ""
  url: https://charts.jetstack.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: traefik
  pass_credentials_all: false
  password: ""
  url: https://helm.traefik.io/traefik
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: external-dns
  pass_credentials_all: false
  password: ""
  url: https://kubernetes-sigs.github.io/external-dns/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: velero
  pass_credentials_all: false
  password: ""
  url: https://vmware-tanzu.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: dex
  pass_credentials_all: false
  password: ""
  url: https://charts.dexidp.io
  username: ""
